# Generated by Django 3.0.6 on 2020-11-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MASEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mas_entry_date', models.DateTimeField(verbose_name='date entry')),
                ('mas_entry_item', models.TextField()),
                ('mas_entry_quantity', models.CharField(max_length=200)),
                ('mas_entry_location', models.TextField()),
                ('mas_entry_remarks', models.TextField()),
            ],
        ),
    ]
